# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b5a37a15-4467-4dbc-88cd-178be1eeccc9";
      fsType = "ext4";
    };

  fileSystems."/mnt/DYSK_0" =
    { device = "/dev/disk/by-uuid/bc079230-f85c-4690-96a2-5b1edc6bd0ee";
      fsType = "ext4";
    };

  fileSystems."/mnt/DYSK_1" =
    { device = "/dev/disk/by-uuid/8b3a43df-058c-43da-8350-61d6ebd2d65c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CED1-B287";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
